# .github/workflows/tests.yml
name: Run Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd price_comparison_server
          echo "Current directory: $(pwd)"
          echo "Files in directory:"
          ls -la
          echo "Installing requirements..."
          pip install -r requirements.txt
          echo "Installed packages:"
          pip list

      - name: Run tests
        run: |
          cd price_comparison_server
          # Set PYTHONPATH to include the current directory
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          echo "PYTHONPATH: $PYTHONPATH"
          echo "Running tests..."
          pytest tests/ -v --cov=. --cov-report=term --cov-report=html
