# .github/workflows/tests.yml
name: Run Tests

# This tells GitHub when to run the tests
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Check out your code
      - uses: actions/checkout@v3

      # Set up Python
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Cache dependencies for faster builds
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov

      # Run tests with coverage
      - name: Run tests with coverage
        run: |
          cd price_comparison_server
          pytest tests/ -v --cov=. --cov-report=xml --cov-report=html

      # Upload coverage reports
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        if: always()
        with:
          file: ./price_comparison_server/coverage.xml
          fail_ci_if_error: false

      # Save test results as artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: price_comparison_server/htmlcov/
